### ISSUE TITLE
Adicionar opção para selecionar o tipo de leito do paciente no formulário de criação/edição de paciente

### ISSUE THREAD

**Issue by alfakini** [fablabjoinville/covid-sc#40]

**Comment by LucasRamos-Developer** [comment]
como faz pra pegar essa feature?

**Comment by LucasRamos-Developer** [comment]
- Na relação paciente leito, tem data de admissao, mas não tem a informação dessa data.
- o paciente tem uma dada de internacao, mas não necessariamente essa é data de entrada no leito

Como ficou?
