### ISSUE TITLE
Criar model SESUser para o usuário admin da Secretaria de Saúde

### ISSUE THREAD

**Issue by alfakini** [fablabjoinville/covid-sc#8]
Este será o usuário utilizado pela secretaria de saúde para acessar os dados. Não sabemos ainda se terá mais de um usuário. Este usuário deve ter acesso ao Django Admin.

**Comment by alfakini** [comment]
Podemos usar o sistema de permissões do Django com dois grupos diferentes ao invés de criar models de usuários diferentes: https://docs.djangoproject.com/en/3.0/topics/auth/default/#permissions-and-authorization

**Comment by arianerocha** [comment]
Pelo que vi não tem dados extras, poderíamos usar o User padrão mesmo, o que acha?
